### PR TITLE
Create Dockerfile_base_amazonlinux

### PR DESCRIPTION
**Pull request by srprash**
This dockerfile will be used to create daemon image with the amazonlinux base image

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by wangzlei — APPROVED** [review]

**Review by willarmiros — APPROVED** [review]
Can we make the name less cumbersome? Like `Dockerfile.amazonlinux` or something?

**Review by mxiamxia — COMMENTED** [review]
LGTM

**Review by anuraaga — COMMENTED** [review]
We should be able to use an ARG and pass `--build-arg` when building instead of duplicating the dockerfile.

**Comment by shogo82148** [comment]
> Rollback Dockerhub image base to AmazonLinux PR #130

Hi, can I have why the image is rollbacked?
Is there any problem on the scratch based image?

**Comment by srprash** [comment]
Hi @shogo82148 
The [Dockerhub image](https://hub.docker.com/layers/amazon/aws-xray-daemon/3.x/images/sha256-403d3f21f8edb884fcb0fff8f328f114973885cbd5b25314e3c7349b3d4626a8?context=explore) was switched back to use the `amazonlinux` base image. When using the `scratch` base image, we unintentionally broke some customers who were relying on some bash tools which are shipped with `amazonlinux` but not with `scratch`. Please see these related issue for more details: https://github.com/aws/aws-xray-daemon/issues/119, https://github.com/aws/aws-xray-daemon/issues/128

Currently, the Dockerhub image is based on `amazonlinux` and the ECR image is based on `scratch` to maintain the existing customer experience. Are you facing any issue with these images?

**Comment by shogo82148** [comment]
@srprash Thank you for your reply. I understood.
 
I'm migrating my service from EC2 to ECS, and looking for a pre-built image of X-Ray daemon.
I have currently no problem, but I was just wondering.

I'm going to use the ECR image, thanks again!

**Pull request merged**
