### PR TITLE
X-Ray Daemon integration testing

### PR DESCRIPTION
**Pull request by srprash**
Testing the end-to-end functionality of Linux binaries (zip, rpm, and deb) on EC2 instances in AWS region `us-west-2`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by srprash** [comment]
The Integration testing jobs are failing due to `Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers`. This is probably because Pull Requests cannot read the repository secrets for safety.

**Comment by srprash** [comment]
I have verified the Integration Testing job of the workflow in my fork: https://github.com/srprash/aws-xray-daemon/actions/runs/2950804224

**Review by atshaw43 — COMMENTED** [review]
LGTM.

How do we verify/see the test run?

**Comment by srprash** [comment]
> How do we verify/see the test run?

As I mentioned in [this comment](https://github.com/aws/aws-xray-daemon/pull/174#issuecomment-1230735510) that I tested it in my fork with the same IAM role as being used here. 
Once this change is merged in (with the override), we will see a new workflow run on the `master` branch here: https://github.com/aws/aws-xray-daemon/actions/workflows/continuous-build.yml?query=branch%3Amaster

**Pull request merged**
